namespace RebuildUs.Modules.RPC;

public enum CustomRPC : byte
{
    // Systems
    ResetVariables = 70,
    ShareOptions,
    WorkaroundSetRoles,
    SetRole,
    AddModifier,
    VersionHandshake,
    UseUncheckedVent,
    UncheckedMurderPlayer,
    UncheckedCmdReportDeadBody,
    UncheckedExilePlayer,
    DynamicMapOption,
    SetGameStarting,
    StopStart,
    ShareGamemode,
    FinishResetVariables,
    FinishSetRole,
    SetLovers,
    OverrideNativeRole,
    UncheckedEndGame,
    UncheckedSetTasks,
    FinishShipStatusBegin,

    // Roles
    EngineerFixLights,
    EngineerFixSubmergedOxygen,
    EngineerUsedRepair,
    ArsonistDouse,
    ArsonistWin,
    CleanBody,
    VultureWin,
    VultureEat,
    ErasePlayerRoles,
    JackalCreatesSidekick,
    SidekickPromotes,
    MedicSetShielded,
    ShieldedMurderAttempt,
    SetFutureShielded,
    TimeMasterShield,
    TimeMasterRewindTime,
    GuesserShoot,
}