namespace RebuildUs.Modules.RPC;

public enum CustomRPC : byte
{
    // Systems
    ResetVariables = 70,
    ShareOptions,
    WorkaroundSetRoles,
    SetRole,
    AddModifier,
    VersionHandshake,
    UseUncheckedVent,
    UncheckedMurderPlayer,
    UncheckedCmdReportDeadBody,
    UncheckedExilePlayer,
    DynamicMapOption = 80,
    SetGameStarting,
    StopStart,
    StopStartSound,
    ShareGamemode,
    FinishResetVariables,
    FinishSetRole,
    SetLovers,
    OverrideNativeRole,
    UncheckedEndGame,
    UncheckedSetTasks = 90,
    FinishShipStatusBegin,

    // Roles
    EngineerFixLights,
    EngineerFixSubmergedOxygen,
    EngineerUsedRepair,
    ArsonistDouse,
    ArsonistWin,
    CleanBody,
    VultureWin,
    VultureEat,
    ErasePlayerRoles = 100,
    JackalCreatesSidekick,
    SidekickPromotes,
    MedicSetShielded,
    ShieldedMurderAttempt,
    SetFutureShielded,
    TimeMasterShield,
    TimeMasterRewindTime,
    GuesserShoot,
    PlaceJackInTheBox,
    LightsOut = 110,
    EvilHackerCreatesMadmate,
    UseAdminTime,
    UseCameraTime,
    UseVitalsTime,
    TrackerUsedTracker,
    SetFutureErased,
    VampireSetBitten,
    ShareRealTasks,
    PolusRandomSpawn,
    Synchronize = 120,
    PlaceCamera,
    SealVent,
    MorphingMorph,
    CamouflagerCamouflage,
    SwapperSwap,
    SwapperAnimate,
    SetFutureSpelled,
    WitchSpellCast,
    PlaceGarlic,
    SUBMERGED_SubmarineOxygenSystem = 130,
    ImpostorPromotesToLastImpostor,
    ShifterShift,
    SetFutureShifted,
    SetShifterType,
    FortuneTellerUsedDivine,
    SUBMERGED_SubmarineElevatorSystemHallwayLeft = 136,
    SUBMERGED_SubmarineElevatorSystemHallwayRight = 137,
    SUBMERGED_SubmarineElevatorSystemLobbyLeft = 138,
    SUBMERGED_SubmarineElevatorSystemLobbyRight = 139,
    SUBMERGED_SubmarineElevatorSystemService = 140,
    SUBMERGED_SubmarinePlayerFloorSystem = 141,
    SUBMERGED_SubmarineSecuritySabotageSystem = 142,
    SUBMERGED_SubmarineSpawnInSystem = 143,
    SUBMERGED_SubmarineBoxCatSystem = 144,
    SheriffKill = 145,
    SheriffKillRequest = 146,


    GamemodeKills,
    CaptureTheFlagWhoTookTheFlag,
    CaptureTheFlagWhichTeamScored,
    PoliceandThiefJail,
    PoliceandThiefFreeThief,
    PoliceandThiefTakeJewel,
    PoliceandThiefDeliverJewel,
    PoliceandThiefRevertedJewelPosition,
    PoliceandThiefsTased,
    HotPotatoTransfer,
    HotPotatoExploded,
    BattleRoyaleShowShoots,

    SUBMERGED_SetCustomData = 210,
    SUBMERGED_RequestChangeFloor = 211,
    SUBMERGED_EngineVent = 213,
    SUBMERGED_OxygenDeath = 214,
}