namespace RebuildUs.Modules.RPC;

internal enum CustomRPC : byte
{
    // Systems
    ResetVariables = 70,
    ShareOptions,
    WorkaroundSetRoles,
    SetRole,
    AddModifier,
    VersionHandshake,
    UseUncheckedVent,
    UncheckedMurderPlayer,
    UncheckedCmdReportDeadBody,
    UncheckedExilePlayer,
    DynamicMapOption = 80,
    SetGameStarting,
    StopStart,
    StopStartSound,
    ShareGamemode,
    FinishResetVariables,
    FinishSetRole,
    SetLovers,
    OverrideNativeRole,
    UncheckedEndGame,
    UncheckedSetTasks = 90,
    FinishShipStatusBegin,

    // Roles
    EngineerFixLights,
    EngineerFixSubmergedOxygen,
    EngineerUsedRepair,
    ArsonistDouse,
    ArsonistWin,
    CleanBody,
    VultureWin,
    VultureEat,
    ErasePlayerRoles = 100,
    JackalCreatesSidekick,
    SidekickPromotes,
    MedicSetShielded,
    ShieldedMurderAttempt,
    SetFutureShielded,
    TimeMasterShield,
    TimeMasterRewindTime,
    GuesserShoot,
    PlaceJackInTheBox,
    LightsOut = 110,
    EvilHackerCreatesMadmate,
    UseAdminTime,
    UseCameraTime,
    UseVitalsTime,
    TrackerUsedTracker,
    SetFutureErased,
    VampireSetBitten,
    ShareRealTasks,
    PolusRandomSpawn,
    Synchronize = 120,
    PlaceCamera,
    SealVent,
    MorphingMorph,
    CamouflagerCamouflage,
    SwapperSwap,
    SwapperAnimate,
    SetFutureSpelled,
    WitchSpellCast,
    PlaceGarlic,
    SubmergedSubmarineOxygenSystem = 130,
    ImpostorPromotesToLastImpostor,
    ShifterShift,
    SetFutureShifted,
    SetShifterType,
    FortuneTellerUsedDivine,
    SubmergedSubmarineElevatorSystemHallwayLeft = 136,
    SubmergedSubmarineElevatorSystemHallwayRight = 137,
    SubmergedSubmarineElevatorSystemLobbyLeft = 138,
    SubmergedSubmarineElevatorSystemLobbyRight = 139,
    SubmergedSubmarineElevatorSystemService = 140,
    SubmergedSubmarinePlayerFloorSystem = 141,
    SubmergedSubmarineSecuritySabotageSystem = 142,
    SubmergedSubmarineSpawnInSystem = 143,
    SubmergedSubmarineBoxCatSystem = 144,
    SheriffKill = 145,
    SheriffKillRequest = 146,

    SubmergedSetCustomData = 210,
    SubmergedRequestChangeFloor = 211,
    SubmergedEngineVent = 213,
    SubmergedOxygenDeath = 214,
}