namespace RebuildUs.Roles;

public enum RoleType : byte
{
    // Crewmate
    Crewmate = 0,
    Shifter,
    Mayor,
    Engineer,
    Sheriff,
    Lighter,
    Detective,
    TimeMaster,
    Medic,
    NiceSwapper,
    Seer,
    Hacker,
    Tracker,
    Snitch,
    Spy,
    SecurityGuard,
    Bait,
    Medium,
    FortuneTeller,
    Suicider,

    // Impostor
    Impostor,
    Godfather,
    Mafioso,
    Janitor,
    Morphing,
    Camouflager,
    Vampire,
    Eraser,
    Trickster,
    Cleaner,
    Warlock,
    BountyHunter,
    Witch,
    Madmate,
    EvilSwapper,

    // Neutral
    Lovers,
    EvilGuesser,
    NiceGuesser,
    Jester,
    Arsonist,
    Jackal,
    Sidekick,

    // Opportunist,
    Vulture,

    // PlagueDoctor,
    // Watcher,
    EvilTracker,
    EvilHacker,

    // Others
    Gm,

    // GameMode
    RedPlayer01,
    RedPlayer02,
    RedPlayer03,
    RedPlayer04,
    RedPlayer05,
    RedPlayer06,
    RedPlayer07,
    BluePlayer01,
    BluePlayer02,
    BluePlayer03,
    BluePlayer04,
    BluePlayer05,
    BluePlayer06,
    BluePlayer07,
    StealerPlayer,
    PolicePlayer01,
    PolicePlayer02,
    PolicePlayer03,
    PolicePlayer04,
    PolicePlayer05,
    PolicePlayer06,
    ThiefPlayer01,
    ThiefPlayer02,
    ThiefPlayer03,
    ThiefPlayer04,
    ThiefPlayer05,
    ThiefPlayer06,
    ThiefPlayer07,
    ThiefPlayer08,
    ThiefPlayer09,
    HotPotato,
    NotPotato01,
    NotPotato02,
    NotPotato03,
    NotPotato04,
    NotPotato05,
    NotPotato06,
    NotPotato07,
    NotPotato08,
    NotPotato09,
    NotPotato10,
    NotPotato11,
    NotPotato12,
    NotPotato13,
    NotPotato14,
    SoloPlayer01,
    SoloPlayer02,
    SoloPlayer03,
    SoloPlayer04,
    SoloPlayer05,
    SoloPlayer06,
    SoloPlayer07,
    SoloPlayer08,
    SoloPlayer09,
    SoloPlayer10,
    SoloPlayer11,
    SoloPlayer12,
    SoloPlayer13,
    SoloPlayer14,
    SoloPlayer15,
    LimePlayer01,
    LimePlayer02,
    LimePlayer03,
    LimePlayer04,
    LimePlayer05,
    LimePlayer06,
    LimePlayer07,
    PinkPlayer01,
    PinkPlayer02,
    PinkPlayer03,
    PinkPlayer04,
    PinkPlayer05,
    PinkPlayer06,
    PinkPlayer07,
    SerialKiller,

    // don't put anything below this
    NoRole = byte.MaxValue,
}
