# Translation Registration Tool
# Auto-generated from add_translation.go

$ErrorActionPreference = "Stop"

$csvPath = "Translations.csv"
$enumPath = "RebuildUs/Localization/TranslateKey.cs"

function Update-Enum {
    param (
        [string]$CsvPath,
        [string]$EnumPath
    )

    try {
        # Read CSV and extract unique keys
        $csvData = Import-Csv -Path $CsvPath -Encoding UTF8
        $keysSet = [System.Collections.Generic.HashSet[string]]::new()

        foreach ($row in $csvData) {
            $k = $row.Key.Trim()
            if (-not [string]::IsNullOrWhiteSpace($k)) {
                [void]$keysSet.Add($k)
            }
        }

        # Sort keys
        $keys = [System.Linq.Enumerable]::OrderBy([string[]]$keysSet, [Func[string, string]] { param($x) $x })

        # Generate enum file
        $sb = New-Object System.Text.StringBuilder
        [void]$sb.AppendLine("// This file is auto-generated by translate-sync.ps1 or add-translation.ps1. Do not edit manually.")
        [void]$sb.AppendLine("namespace RebuildUs.Localization;")
        [void]$sb.AppendLine("")
        [void]$sb.AppendLine("public enum TrKey")
        [void]$sb.AppendLine("{")
        [void]$sb.AppendLine("    None,")

        foreach ($k in $keys) {
            [void]$sb.AppendLine("    $k,")
        }

        [void]$sb.AppendLine("}")

        # Ensure directory exists
        $enumDir = Split-Path -Parent $EnumPath
        if (-not (Test-Path $enumDir)) {
            New-Item -ItemType Directory -Path $enumDir -Force | Out-Null
        }

        # Write with UTF8 encoding (without BOM)
        $utf8NoBom = New-Object System.Text.UTF8Encoding $false
        [System.IO.File]::WriteAllText($EnumPath, $sb.ToString(), $utf8NoBom)

        Write-Host "Updated $EnumPath" -ForegroundColor Cyan
    }
    catch {
        Write-Host "Error updating enum: $_" -ForegroundColor Red
    }
}

Write-Host "Translation Registration Tool (Press Enter with empty key to finish)" -ForegroundColor Cyan

while ($true) {
    Write-Host ""
    $key = Read-Host "Enter Translation Key"
    $key = $key.Trim()

    if ([string]::IsNullOrWhiteSpace($key)) {
        break
    }

    $enText = Read-Host "Enter English Text"
    $enText = $enText.Trim()

    # Append to CSV
    try {
        # Read existing CSV to check for duplicates
        if (Test-Path $csvPath) {
            $existingData = Import-Csv -Path $csvPath -Encoding UTF8
            $duplicate = $existingData | Where-Object { $_.Key -eq $key }

            if ($duplicate) {
                Write-Host "Warning: Key '$key' already exists in the CSV. Appending anyway..." -ForegroundColor Yellow
            }
        }

        # Append new row (Key, English, Japanese)
        $newRow = [PSCustomObject]@{
            Key      = $key
            English  = $enText
            Japanese = ""
        }

        # Export with append
        $newRow | Export-Csv -Path $csvPath -Append -NoTypeInformation -Encoding UTF8

        Write-Host "Added new translation: [$key] -> `"$enText`"" -ForegroundColor Green

        # Update TranslateKey.cs immediately
        Update-Enum -CsvPath $csvPath -EnumPath $enumPath

        Write-Host "TranslateKey.cs has been updated. You can now use the new key in your code." -ForegroundColor Green
    }
    catch {
        Write-Host "Error: $_" -ForegroundColor Red
        continue
    }
}

Write-Host ""
Write-Host "Finished adding translations." -ForegroundColor Green
Write-Host "Note: Please run 'translate-sync.ps1' or 'Sync Translations' task when you are ready to update JSON files." -ForegroundColor Yellow