# This script synchronizes translations from Translations.csv to JSON files and generates C# enum.
# Auto-generated from translate_sync.go

$ErrorActionPreference = "Stop"

# 1. Read CSV
Write-Host "Reading Translations.csv..."

$csvPath = "Translations.csv"
if (-not (Test-Path $csvPath))
{
    Write-Error "Error: Translations.csv not found"
    exit 1
}

$csvContent = Import-Csv -Path $csvPath -Encoding UTF8

$translations = [ordered]@{ }
$keys = @()

foreach ($row in $csvContent)
{
    $key = $row.Key.Trim()

    if ( [string]::IsNullOrWhiteSpace($key))
    {
        continue
    }

    # Handle duplicates
    if ( $translations.Contains($key))
    {
        Write-Warning "Warning: Duplicate key found: $key. Using the latest entry."
    }
    else
    {
        $keys += $key
    }

    # Replace \n with actual newline
    $english = $row.English -replace '\\n', "`n"
    $japanese = $row.Japanese -replace '\\n', "`n"

    $translations[$key] = @{
        Key = $key
        English = $english
        Japanese = $japanese
    }
}

# Sort keys to maintain stable output
$keys = $keys | Sort-Object

Write-Host "Found $( $keys.Count ) translation keys"

# 2. Generate JSON Files
function Generate-JSON
{
    param (
        [string]$Path,
        [array]$Keys,
        [hashtable]$Translations,
        [string]$Language
    )

    $data = [ordered]@{ }
    foreach ($k in $Keys)
    {
        $val = $Translations[$k][$Language]
        if (-not [string]::IsNullOrWhiteSpace($val))
        {
            $data[$k] = $val
        }
    }

    # Convert to JSON with proper formatting
    $json = $data | ConvertTo-Json -Depth 10

    # Ensure directory exists
    $dir = Split-Path -Parent $Path
    if (-not (Test-Path $dir))
    {
        New-Item -ItemType Directory -Path $dir -Force | Out-Null
    }

    # Write with UTF8 encoding (without BOM)
    $utf8NoBom = New-Object System.Text.UTF8Encoding $false
    [System.IO.File]::WriteAllText($Path, $json, $utf8NoBom)

    Write-Host "Generated $Path"
}

Generate-JSON -Path "RebuildUs/Localization/Translations/English.json" -Keys $keys -Translations $translations -Language "English"
Generate-JSON -Path "RebuildUs/Localization/Translations/Japanese.json" -Keys $keys -Translations $translations -Language "Japanese"

# 3. Generate C# Enum
Write-Host "Generating C# enum..."

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("// This file is auto-generated by translate-sync.ps1. Do not edit manually.")
[void]$sb.AppendLine("namespace RebuildUs.Localization;")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("public enum TrKey")
[void]$sb.AppendLine("{")
[void]$sb.AppendLine("    None,")

foreach ($k in $keys)
{
    [void]$sb.AppendLine("    $k,")
}

[void]$sb.AppendLine("}")

$enumPath = "RebuildUs/Localization/TrKey.cs"
$enumDir = Split-Path -Parent $enumPath
if (-not (Test-Path $enumDir))
{
    New-Item -ItemType Directory -Path $enumDir -Force | Out-Null
}

$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText($enumPath,$sb.ToString(), $utf8NoBom)

Write-Host "Generated $enumPath"
Write-Host ""
Write-Host "Synchronization complete." -ForegroundColor Green