using Impostor.Api.Games;
using RebuildUs.Impostor.Handlers;
using RebuildUs.Impostor.Services;
using Impostor.Api.Events.Managers;
using Microsoft.Extensions.Logging;
using System.Security.Cryptography;
using System.Diagnostics;

namespace RebuildUs.Impostor;

public class GameCodeManager : IGameCodeManager
{
    private static readonly HashSet<char> V2Chars = [.. "ABCDEFGHIJKLMNOPQRSTUVWXYZ"];

    private readonly List<GameCode> _codes;

    private readonly HashSet<GameCode> _inUse = [];

    private readonly object _sync = new();

    private readonly ILogger<IGameCodeManager> _logger;

    private readonly IGameCodeFactory _codeFactory;

    public string Path => System.IO.Path.GetFullPath("RebuildUs.Codes");

    public int SixCharCodes { get; }

    public int FourCharCodes { get; }

    public GameCodeManager(ILogger<GameCodeManager> logger, IGameCodeFactory codeFactory, IEventManager eventManager, IDiscordService discordService, IPlayerMappingService mappingService, ILogger<GameEventListener> listenerLogger)
    {
        _logger = logger;
        _codeFactory = codeFactory;
        logger.LogInformation("RebuildUs.Codes: Reading files from {Path}", Path);

        var validCodes = Read().ToList();
        if (validCodes.Count == 0)
        {
            _codes = [];
            return;
        }

        validCodes.Shuffle();

        FourCharCodes = validCodes.Count(code => code.Code.Length == 4);
        SixCharCodes = validCodes.Count(code => code.Code.Length == 6);

        _codes = validCodes;

        eventManager.RegisterListener(new GameEventListener(this, discordService, mappingService, listenerLogger));
    }

    private IEnumerable<GameCode> Read()
    {
        var filePath = System.IO.Path.Combine(Path, "RoomCodes.txt");

        if (!File.Exists(filePath))
        {
            _logger.LogWarning("RebuildUs.Codes: RoomCodes.txt not found at {Path}", filePath);
            return [];
        }

        var comment = new[] { "--" };
        var codes = new HashSet<GameCode>();

        const StringSplitOptions splitOptions = StringSplitOptions.None;

        var stopwatch = Stopwatch.StartNew();
        var invalid = 0;

        _logger.LogInformation("RebuildUs.Codes: reading \"{File}\"", filePath);

        foreach (var line in File.ReadLines(filePath))
        {
            if (string.IsNullOrWhiteSpace(line))
            {
                continue;
            }

            var trimStart = line.TrimStart();
            if (trimStart.StartsWith(comment[0]))
            {
                continue;
            }

            var codeStr = trimStart.Split(comment, 2, splitOptions)[0].TrimEnd();

            if ((codeStr.Length != 6 && codeStr.Length != 4) || codeStr.Any(c => !V2Chars.Contains(c)))
            {
                if (invalid++ < 5)
                {
                    _logger.LogWarning("RebuildUs.Codes: The code \"{code}\" is invalid!", codeStr);
                }

                if (invalid == 6)
                {
                    _logger.LogWarning("RebuildUs.Codes: Found more invalid codes, please check your input files and clean them up");
                }

                continue;
            }

            var code = new GameCode(codeStr);
            if (!code.IsInvalid && !codes.Contains(code))
            {
                codes.Add(code);
            }
            else
            {
                invalid++;
            }
        }

        if (codes.Count == 0)
        {
            _logger.LogWarning("RebuildUs.Codes: No valid codes found in RoomCodes.txt.");
            return [];
        }

        stopwatch.Stop();
        _logger.LogInformation("RebuildUs.Codes: Finished loading file in {Seconds} seconds, with {invalids} invalid codes.", stopwatch.Elapsed.TotalSeconds, invalid);

        return codes;
    }

    public GameCode Get()
    {
        lock (_sync)
        {
            if (_codes.Count == 0)
            {
                _logger.LogWarning("RebuildUs.Codes: Ran out of codes!");
                return _codeFactory.Create();
            }

            var index = RandomNumberGenerator.GetInt32(0, _codes.Count);
            var code = _codes[index];

            _codes.RemoveAt(index);
            _inUse.Add(code);

            return code;
        }
    }

    public void Release(GameCode code)
    {
        lock (_sync)
        {
            if (!_inUse.Contains(code))
            {
                return; // generated by the factory
            }

            _inUse.Remove(code);
            _codes.Add(code);
        }
    }
}