package main

import (
	"bufio"
	"encoding/csv"
	"fmt"
	"os"
	"sort"
	"strings"
)

func main() {
	reader := bufio.NewReader(os.Stdin)

	fmt.Print("Enter Translation Key: ")
	key, _ := reader.ReadString('\n')
	key = strings.TrimSpace(key)

	if key == "" {
		fmt.Println("Error: Key cannot be empty.")
		return
	}

	fmt.Print("Enter English Text: ")
	enText, _ := reader.ReadString('\n')
	enText = strings.TrimSpace(enText)

	csvPath := "Translations.csv"

	// Open file in append mode
	f, err := os.OpenFile(csvPath, os.O_APPEND|os.O_WRONLY, 0644)
	if err != nil {
		fmt.Printf("Error opening CSV: %v\n", err)
		return
	}
	defer f.Close()

	writer := csv.NewWriter(f)

	// Escape backslashes if any (though typically adding literal \n manually in args is common)
	// For simplicity, we just write the raw string.
	// If the user wants actual newlines, they should pass "\n" as part of the string.

	err = writer.Write([]string{key, enText, ""}) // Japanese is empty by default
	if err != nil {
		fmt.Printf("Error writing to CSV: %v\n", err)
		return
	}

	writer.Flush()
	fmt.Printf("Added new translation: [%s] -> \"%s\"\n", key, enText)

	// Update TranslateKey.cs immediately
	updateEnum(csvPath, "RebuildUs/Localization/TranslateKey.cs")

	fmt.Println("TranslateKey.cs has been updated. You can now use the new key in your code.")
	fmt.Println("Note: Please run 'Sync Translations' task when you are ready to update JSON files.")
}

func updateEnum(csvPath, enumPath string) {
	f, err := os.Open(csvPath)
	if err != nil {
		fmt.Printf("Error opening CSV for enum update: %v\n", err)
		return
	}
	defer f.Close()

	reader := csv.NewReader(f)
	reader.LazyQuotes = true
	// Skip header
	_, _ = reader.Read()

	keysMap := make(map[string]struct{})
	for {
		record, err := reader.Read()
		if err != nil {
			break
		}
		k := strings.TrimSpace(record[0])
		if k != "" {
			keysMap[k] = struct{}{}
		}
	}

	var keys []string
	for k := range keysMap {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var sb strings.Builder
	sb.WriteString("// This file is auto-generated by translate_sync.go or add_translation.go. Do not edit manually.\n")
	sb.WriteString("namespace RebuildUs.Localization;\n\n")
	sb.WriteString("public enum TranslateKey\n")
	sb.WriteString("{\n")
	sb.WriteString("    None,\n")
	for _, k := range keys {
		sb.WriteString(fmt.Sprintf("    %s,\n", k))
	}
	sb.WriteString("}\n")

	_ = os.WriteFile(enumPath, []byte(sb.String()), 0644)
	fmt.Printf("Updated %s\n", enumPath)
}
