package main

import (
	"encoding/csv"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"sort"
	"strings"
)

type Translation struct {
	Key      string
	English  string
	Japanese string
}

func main() {
	// 1. Read CSV
	f, err := os.Open("Translations.csv")
	if err != nil {
		fmt.Printf("Error opening CSV: %v\n", err)
		return
	}
	defer f.Close()

	reader := csv.NewReader(f)
	reader.LazyQuotes = true
	reader.TrimLeadingSpace = true
	// Skip header
	_, err = reader.Read()
	if err != nil {
		fmt.Printf("Error reading header: %v\n", err)
		return
	}

	translations := make(map[string]Translation)
	var keys []string

	for {
		record, err := reader.Read()
		if err == io.EOF {
			break
		}
		if err != nil {
			fmt.Printf("Error reading record: %v\n", err)
			continue
		}

		key := strings.TrimSpace(record[0])
		if key == "" {
			continue
		}

		// Handle duplicates
		if _, exists := translations[key]; exists {
			fmt.Printf("Warning: Duplicate key found: %s. Using the latest entry.\n", key)
		} else {
			keys = append(keys, key)
		}

		translations[key] = Translation{
			Key:      key,
			English:  strings.ReplaceAll(record[1], "\\n", "\n"),
			Japanese: strings.ReplaceAll(record[2], "\\n", "\n"),
		}
	}

	// Sort keys to maintain stable output
	sort.Strings(keys)

	// 2. Generate JSON Files
	generateJSON("RebuildUs/Localization/Translations/English.json", keys, translations, func(t Translation) string { return t.English })
	generateJSON("RebuildUs/Localization/Translations/Japanese.json", keys, translations, func(t Translation) string { return t.Japanese })

	// 3. Generate C# Enum
	generateEnum("RebuildUs/Localization/TranslateKey.cs", keys)

	fmt.Println("Synchronization complete.")
}

func generateJSON(path string, keys []string, translations map[string]Translation, getValue func(Translation) string) {
	data := make(map[string]string)
	// Use ordered keys to create a map for JSON (Go maps are unordered, so we use a map and then marshal)
	// MarshalIndent will sort keys alphabetically by default.
	for _, k := range keys {
		val := getValue(translations[k])
		if val != "" {
			data[k] = val
		}
	}

	file, _ := json.MarshalIndent(data, "", "  ")
	_ = os.WriteFile(path, file, 0644)
	fmt.Printf("Generated %s\n", path)
}

func generateEnum(path string, keys []string) {
	var sb strings.Builder
	sb.WriteString("// This file is auto-generated by translate_sync.go. Do not edit manually.\n")
	sb.WriteString("namespace RebuildUs.Localization;\n\n")
	sb.WriteString("public enum TranslateKey\n")
	sb.WriteString("{\n")
	sb.WriteString("    None,\n")

	for _, k := range keys {
		sb.WriteString(fmt.Sprintf("    %s,\n", k))
	}

	sb.WriteString("}\n")

	_ = os.WriteFile(path, []byte(sb.String()), 0644)
	fmt.Printf("Generated %s\n", path)
}
